name: cache_cargo
description: Cache Cargo dependencies and workspace build output
runs:
  using: composite
  steps:
    - uses: actions/cache@v6
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('rust-toolchain.toml', '**/Cargo.toml', 'Cargo.lock') }}
        restore-keys: ${{ runner.os }}-cargo-
