[package]
name = "motrs_wasm"
version = "0.1.0"
authors = ["uzushino <torattoria.mamiya@gmail.com>"]
edition.workspace = true
rust-version.workspace = true

[dependencies]
motrs = { path = "../motrs" }
wasm-bindgen.workspace = true
serde.workspace = true
gloo-utils.workspace = true
uuid = { workspace = true, features = ["js"] }

[lib]
crate-type = ["cdylib", "lib"]
name = "motrs_wasm"
bench = false
